# Generated by Django 5.0.6 on 2024-07-15 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
